# A string used to distinguish different Supabase projects on the same host.
project_id = "wavesync-seafarer"

[api]
enabled = true
# Port to use for the API URL.
port = 54321
# Schemas to expose in your API. Tables, views and stored procedures in this schema will get API endpoints.
# public and storage are always included.
schemas = ["public", "storage", "graphql_public"]
# Extra schemas to add to the search_path of every request.
extra_search_path = ["public", "extensions"]
# The maximum number of rows returns from a table, view, or stored procedure without an explicit limit.
max_rows = 1000

[db]
# Port to use for the local database URL.
port = 54322
# Port used by db diff command to initialise the shadow database.
shadow_port = 54320
# The database major version to use. This has to be the same as your remote database's major version.
major_version = 15

[db.pooler]
enabled = false
# Port to use for the local connection po0ler.
port = 54329
# Specifies when a server connection can be reused by other clients.
# https://www.postgresql.org/docs/current/runtime-config-connection.html#RUNTIME-CONFIG-CONNECTION
pool_mode = "transaction"
# How many server connections to allow per user/database pair.
default_pool_size = 20
# Maximum number of client connections allowed.
max_client_conn = 100

[realtime]
enabled = true
# Bind realtime via either IPv4 or IPv6. (default: IPv6)
# ip_version = "IPv6"

[studio]
enabled = true
# Port to use for Supabase Studio.
port = 54323
# External URL of the API server that frontend connects to.
api_url = "http://127.0.0.1"
# OpenAPI spec file to populate template values
openapi_url = "openapi.yml"

# Email testing server. Emails sent with the local dev setup are not actually sent - rather, they
# are monitored, and you can view the emails that would have been sent from the web interface.
[inbucket]
enabled = true
# Port to use for the email testing server web interface.
port = 54324
# Uncomment to expose additional ports for testing user applications that send emails.
# smtp_port = 54325
# pop3_port = 54326

[storage]
enabled = true
# The maximum file size allowed (e.g. "5MB", "500KB").
file_size_limit = "50MiB"

[auth]
enabled = true
# The base URL of your website. Used as an allow-list for redirects and for constructing URLs used
# in emails.
site_url = "http://localhost:3000"
# A list of *exact* URLs that auth providers are permitted to redirect to post authentication.
additional_redirect_urls = ["https://localhost:3000"]
# How long tokens are valid for, in seconds. Defaults to 3600 (1 hour), maximum 604800 (1 week).
jwt_expiry = 3600
# If disabled, the refresh token will never expire.
enable_refresh_token_rotation = true
# Allows refresh tokens to be reused after expiry, up to the specified interval in seconds.
# Requires enable_refresh_token_rotation = true.
refresh_token_reuse_interval = 10
# Allow/disallow new user signups to your project.
enable_signup = true

[auth.email]
# Allow/disallow new user signups via email to your project.
enable_signup = true
# If enabled, a user will be required to confirm any email change on both the old, and new email addresses. If disabled, only the new email is required to confirm.
double_confirm_changes = true
# If enabled, users need to confirm their email address before signing in.
enable_confirmations = false

# Uncomment to customize email template
# [auth.email.template.invite]
# subject = "You have been invited"
# content_path = "./supabase/templates/invite.html"

[auth.sms]
# Allow/disallow new user signups via SMS to your project.
enable_signup = true
# If enabled, users need to confirm their phone number before signing in.
enable_confirmations = false

# Use pre-defined map of phone number to OTP for testing.
# [auth.sms.test_otp]
# 4152127777 = "123456"

# Configure one of the supported SMS providers: `twilio`, `messagebird`, `textlocal`, `vonage`.
# [auth.sms.twilio]
# account_sid = ""
# message_service_sid = ""

[auth.external.apple]
enabled = true
# OAuth client secret from Apple
secret = ""
# Overrides the default auth redirectUrl.
redirect_uri = ""
# Overrides the default auth provider URL. Used to support self-hosted gitlab, single-tenant Azure.
url = ""

[auth.external.azure]
enabled = false
secret = ""
redirect_uri = ""
url = ""

[auth.external.bitbucket]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.discord]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.facebook]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.github]
enabled = true
secret = ""
redirect_uri = ""

[auth.external.gitlab]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.google]
enabled = true
secret = ""
redirect_uri = ""

[auth.external.keycloak]
enabled = false
secret = ""
redirect_uri = ""
url = ""

[auth.external.linkedin]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.notion]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.twitch]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.twitter]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.slack]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.spotify]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.workos]
enabled = false
secret = ""
redirect_uri = ""

[auth.external.zoom]
enabled = false
secret = ""
redirect_uri = ""

[analytics]
enabled = false
port = 54327
vector_port = 54328
# Configure one of the supported backends: `postgres`, `bigquery`.
backend = "postgres"


